add TabButton htmlable
Team-Nifty-GmbH/flux-core pull request #193
Opened 2023-11-08 14:43 UTC by patrickweh

fix TicketCreatedNotificationListener.php

2023-11-08 17:09 UTC, SirSplasch requested changes

2023-11-08 17:09 UTC, SirSplasch commented on src/Console/Commands/Init/InitPermissions.php
> +            if(! in_array(WithTabs::class, class_uses_recursive($component))) {
whitespace after if

2023-11-08 17:09 UTC, SirSplasch commented on src/Console/Commands/Init/InitPermissions.php
> +            }
new line after }

2023-11-08 17:09 UTC, SirSplasch commented on src/Console/Commands/Init/InitPermissions.php
>              Permission::query()->whereKey($id)->delete();
why not only one delete statement, which deletes all?

2023-11-09 06:50 UTC, patrickweh commented on resources/views/livewire/order/order.blade.php
>          <div class="w-full lg:col-start-1 xl:col-span-2 xl:flex xl:space-x-6">
yes, because the sections right and left persist for every tab

2023-11-09 14:47 UTC, SirSplasch approved these changes

2023-11-09 14:47 UTC, merged