add settings for work time types
Team-Nifty-GmbH/flux-core pull request #234
Opened 2023-12-11 14:37 UTC by patrickweh

add settings for payment types

add settings for vat rates

2023-12-13 11:13 UTC, SirSplasch requested changes
Change all:
```               
                ->attributes(
                    ['wire:click' => 'edit']
                ),
```
to
```                
                ->attributes([
                    'wire:click' => 'edit',
                ]),
```

2023-12-13 11:13 UTC, SirSplasch commented on src/Livewire/Settings/PaymentTypes.php
> +            DeletepaymentType::make($this->paymentType->toArray())
class name in upper camel case

2023-12-13 11:13 UTC, SirSplasch commented on src/Livewire/Settings/SerialNumberRanges.php
> +                ->when(CreateVatRate::canPerformAction(false))
CreateVatRate on SerialNumerRanges?

2023-12-13 11:13 UTC, SirSplasch commented on lang/de.json
Add missing translations.
None of the keys in the newly created delete confirm dialogs are being translated

2023-12-13 20:13 UTC, patrickweh commented on lang/de.json
added a wire:confirm.delete as a translation key for english and german.

usage like this:

`wire:confirm.icon.error="{{ trans('wire:confirm.delete', ['model' => __('Serial Number Range')]) }}"
`

2023-12-14 14:44 UTC, SirSplasch requested changes
why user trans() instead of __()?

2023-12-14 14:44 UTC, SirSplasch commented on src/Livewire/Settings/PaymentTypes.php
> +                    ['wire:click' => 'edit(record.id)']
reformat

2023-12-14 14:44 UTC, SirSplasch commented on src/Livewire/Settings/SerialNumberRanges.php
> +                    ['wire:click' => 'edit(record.id)']
reformat

2023-12-14 14:44 UTC, SirSplasch commented on src/Livewire/Settings/VatRates.php
> +                    ['wire:click' => 'edit(record.id)']
reformat

2023-12-14 14:44 UTC, SirSplasch commented on src/Livewire/Settings/WorkTimeTypes.php
> +                    ['wire:click' => 'edit(record.id)']
reformat

2023-12-15 14:14 UTC, SirSplasch approved these changes

2023-12-16 07:19 UTC, merged