add commission credit note order type id
Team-Nifty-GmbH/flux-core pull request #652
Opened 2024-11-13 09:21 UTC by patrickweh

2024-11-14 16:02 UTC, SirSplasch requested changes

2024-11-14 16:02 UTC, SirSplasch commented on src/Rulesets/Client/CreateClientRuleset.php
> +                    ->where('order_type_enum', OrderTypeEnum::Refund),
exclude inactive or hidden order types?

2024-11-14 16:02 UTC, SirSplasch commented on src/Rulesets/Client/UpdateClientRuleset.php
> +                    ->where('order_type_enum', OrderTypeEnum::Refund),
exclude inactive or hidden order types?

2024-11-14 17:01 UTC, patrickweh commented on src/Rulesets/Client/CreateClientRuleset.php
> +                    ->where('order_type_enum', OrderTypeEnum::Refund),
hidden shouldnt be excluded here…

2024-11-18 08:08 UTC, SirSplasch approved these changes

2024-11-18 08:41 UTC, merged