add make commands
Team-Nifty-GmbH/flux-core pull request #711
Opened 2024-12-19 12:53 UTC by patrickweh

2024-12-19 13:57 UTC, patrickweh commented on src/Console/Commands/stubs/livewire.form.stub
> +class DummyClass extends FluxForm
comes from the base GeneratorCommand

2024-12-19 13:57 UTC, patrickweh commented on src/Console/Commands/MakeForm.php
> +        {--force}
overrides the form if already exists, comes from base command

2024-12-19 17:08 UTC, SirSplasch requested changes

2024-12-19 17:08 UTC, SirSplasch commented on src/Console/Commands/MakeAction.php
> +        $variableName = Str::of($pureName)->after('Create')->lcfirst();
new line after }

2024-12-20 09:05 UTC, SirSplasch approved these changes

2024-12-20 09:20 UTC, merged