refactor action broadcasting
Team-Nifty-GmbH/flux-core pull request #718
Opened 2024-12-22 16:01 UTC by patrickweh

2025-01-12 02:52 UTC, SirSplasch requested changes

2025-01-12 02:52 UTC, SirSplasch commented on src/Traits/Action/HasActionEvents.php
> +    public static function booting(QueuedClosure|callable|array|string $callback): void
why are these methods public and not protected?

2025-01-12 02:52 UTC, SirSplasch commented on src/Traits/Action/HasActionEvents.php
Why did you get rid of the NullDispatcher?

2025-01-12 02:52 UTC, SirSplasch commented on src/Actions/FluxAction.php
> -    public function __serialize(): array
Why remove __serialize() and __unserialize() methods? These don't do any harm. If someone wants to serialize an action this is necessary, or when an action is passed to a constructor of an aysnc job it will be serialized.

2025-01-12 02:52 UTC, SirSplasch commented on src/Traits/Action/BroadcastsActionEvents.php
> +            $payload['result'] = $this->result instanceof Serializable
but what if $this->result is a simple data type, like an integer, boolean, etc. Then this information is lost, as all will be null.

2025-01-12 02:52 UTC, SirSplasch commented on src/Traits/Action/BroadcastsActionEvents.php
This trait is currently not used anywhere (as far as I can see). Is this intended?

2025-01-12 02:52 UTC, SirSplasch commented on src/Events/BroadcastableActionEventOccurred.php
> +    public function __construct(FluxAction $action, string $event)
needs this all to be done? Cloning the action and serializing these bits one by one?
In my head there must be an easier solution, but I am not that deep into this, I just review this on a little below surface level.

2025-01-15 14:43 UTC, patrickweh commented on src/Traits/Action/HasActionEvents.php
> +    public static function booting(QueuedClosure|callable|array|string $callback): void
to make it possible to register an event from a ServiceProvider eg `CreateContact::booting(fn($asdf) => dd($asdf));`

2025-01-15 14:46 UTC, patrickweh commented on src/Events/BroadcastableActionEventOccurred.php
> +    public function __construct(FluxAction $action, string $event)
the problem is that result is mixed, could be PDO which cant be serialized but still needs the actionevent to trigger

2025-01-15 14:48 UTC, patrickweh commented on src/Traits/Action/BroadcastsActionEvents.php
thats intended, for now i dont have actions that need broadcasting (i had but solved it in a different way)

2025-01-16 13:36 UTC, SirSplasch requested changes

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/HasActionEvents.php
> +        if (! isset(static::$dispatcher)) {
is_null(static::$dispatcher)

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/HasActionEvents.php
> +    public static function setEventDispatcher(?Dispatcher $dispatcher = null): void
move the last three methods above registerActionEvent()

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/HasActionEvents.php
> +        $this->setEventDispatcher(app('events'));
shouldn't this method be called like a static method static::setEventDispatcher()?

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/BroadcastsActionEvents.php
> +    public static function getBroadcastChannel(): string
move below boot

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/BroadcastsActionEvents.php
protected methods after public

2025-01-16 13:36 UTC, SirSplasch commented on src/Traits/Action/BroadcastsActionEvents.php
> +                    is_int($result) || is_float($result) || is_string($result) || is_bool($result)
Its not perfect but I guess its fine.
Like an array containing only simple data types would normally be totally fine, but ok.

2025-01-16 13:36 UTC, SirSplasch commented on src/Events/BroadcastableActionEventOccurred.php
I will be honest, I don't know if this works, if it doesn't it needs to be fixed at a later point.

2025-01-17 14:23 UTC, SirSplasch approved these changes

2025-01-17 14:40 UTC, merged