Enhance widgets
Team-Nifty-GmbH/flux-core pull request #724
Opened 2024-12-29 16:32 UTC by patrickweh

2025-01-11 23:04 UTC, SirSplasch requested changes

2025-01-11 23:04 UTC, SirSplasch commented on src/Livewire/Widgets/OpenDeliveries.php
> +        $this->sum = $metric;
why use extra variable? Can just do $this->sum = resolve_static()

2025-01-13 17:06 UTC, patrickweh commented on src/Support/Widgets/ValueList.php
> +    public function showMore(): void {}
nope, maybe i dont want to show more in the widget. i dont want to throw an error here

2025-01-14 02:00 UTC, SirSplasch approved these changes

2025-01-14 06:34 UTC, merged